[2022-11-30T12:14:22.338+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: a_start_dag.read manual__2022-11-30T12:14:20.102985+00:00 [queued]>
[2022-11-30T12:14:22.355+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: a_start_dag.read manual__2022-11-30T12:14:20.102985+00:00 [queued]>
[2022-11-30T12:14:22.355+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T12:14:22.355+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-30T12:14:22.355+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T12:14:22.377+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): read> on 2022-11-30 12:14:20.102985+00:00
[2022-11-30T12:14:22.385+0000] {standard_task_runner.py:55} INFO - Started process 10264 to run task
[2022-11-30T12:14:22.389+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'a_start_dag', 'read', 'manual__2022-11-30T12:14:20.102985+00:00', '--job-id', '1058', '--raw', '--subdir', 'DAGS_FOLDER/start_dag.py', '--cfg-path', '/tmp/tmpveb9s748']
[2022-11-30T12:14:22.391+0000] {standard_task_runner.py:83} INFO - Job 1058: Subtask read
[2022-11-30T12:14:22.458+0000] {task_command.py:376} INFO - Running <TaskInstance: a_start_dag.read manual__2022-11-30T12:14:20.102985+00:00 [running]> on host ab28c0b87467
[2022-11-30T12:14:22.547+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=a_start_dag
AIRFLOW_CTX_TASK_ID=read
AIRFLOW_CTX_EXECUTION_DATE=2022-11-30T12:14:20.102985+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-30T12:14:20.102985+00:00
[2022-11-30T12:14:23.865+0000] {logging_mixin.py:137} INFO -       Game Number   "Game Length"
0               1              30
1               2              29
2               3              31
3               4              16
4               5              24
...           ...             ...
9995         9996              14
9996         9997              16
9997         9998              29
9998         9999               9
9999        10000              59

[10000 rows x 2 columns]
[2022-11-30T12:14:23.866+0000] {python.py:177} INFO - Done. Returned value was:       Game Number   "Game Length"
0               1              30
1               2              29
2               3              31
3               4              16
4               5              24
...           ...             ...
9995         9996              14
9996         9997              16
9997         9998              29
9998         9999               9
9999        10000              59

[10000 rows x 2 columns]
[2022-11-30T12:14:23.880+0000] {xcom.py:600} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2022-11-30T12:14:23.881+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2385, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 212, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 597, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2022-11-30T12:14:23.893+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=a_start_dag, task_id=read, execution_date=20221130T121420, start_date=20221130T121422, end_date=20221130T121423
[2022-11-30T12:14:23.907+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1058 for task read (Object of type DataFrame is not JSON serializable; 10264)
[2022-11-30T12:14:23.931+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-30T12:14:23.959+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
