[2022-12-01T07:13:36.566+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: a_start_dag.read_file manual__2022-12-01T07:13:28.151021+00:00 [queued]>
[2022-12-01T07:13:36.579+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: a_start_dag.read_file manual__2022-12-01T07:13:28.151021+00:00 [queued]>
[2022-12-01T07:13:36.579+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-01T07:13:36.579+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-01T07:13:36.579+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-01T07:13:36.593+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): read_file> on 2022-12-01 07:13:28.151021+00:00
[2022-12-01T07:13:36.601+0000] {standard_task_runner.py:55} INFO - Started process 319 to run task
[2022-12-01T07:13:36.605+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'a_start_dag', 'read_file', 'manual__2022-12-01T07:13:28.151021+00:00', '--job-id', '1149', '--raw', '--subdir', 'DAGS_FOLDER/start_dag.py', '--cfg-path', '/tmp/tmps6ep95nc']
[2022-12-01T07:13:36.607+0000] {standard_task_runner.py:83} INFO - Job 1149: Subtask read_file
[2022-12-01T07:13:36.684+0000] {task_command.py:376} INFO - Running <TaskInstance: a_start_dag.read_file manual__2022-12-01T07:13:28.151021+00:00 [running]> on host 3859ff78a683
[2022-12-01T07:13:36.757+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=a_start_dag
AIRFLOW_CTX_TASK_ID=read_file
AIRFLOW_CTX_EXECUTION_DATE=2022-12-01T07:13:28.151021+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-01T07:13:28.151021+00:00
[2022-12-01T07:13:36.759+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-01T07:13:36.759+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'mv file.csv files/ ']
[2022-12-01T07:13:36.777+0000] {subprocess.py:86} INFO - Output:
[2022-12-01T07:13:36.786+0000] {subprocess.py:93} INFO - mv: cannot stat 'file.csv': No such file or directory
[2022-12-01T07:13:36.787+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2022-12-01T07:13:36.798+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-12-01T07:13:36.803+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=a_start_dag, task_id=read_file, execution_date=20221201T071328, start_date=20221201T071336, end_date=20221201T071336
[2022-12-01T07:13:36.819+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1149 for task read_file (Bash command failed. The command returned a non-zero exit code 1.; 319)
[2022-12-01T07:13:36.856+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-01T07:13:36.876+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
